### ISSUE TITLE
Should mag limits be calculated at t_ccd or at t_ccd plus model error?

### ISSUE THREAD

**Issue by jeanconn** [sot/starcheck#134]

**Comment by taldcroft** [comment]
t_ccd.

**Comment by jeanconn** [comment]
Asking because if I want to say something like "stars are OK with margin" I don't have good intuition for, say, how much a half of a degree changes the magnitude limits and probabilities.

**Comment by taldcroft** [comment]
We have sufficient margin built in to the rest of the system.

**Comment by jeanconn** [comment]
On catalogs in general we don't have defined limits to have defined margin on those limits (except for the new acquisition probability limit).  Agreed that evaluating at a different t_ccd would just be confusing, but wondering here about other ways to measure and show margin.

**Comment by taldcroft** [comment]
We could do the prob calculations while sampling over the probability distribution of T_ccd.  And for that matter sample star magnitudes.  That will work and be more complete.  I don't think it is a priority right now.
