### ISSUE TITLE
Bump red / yellow temperature limits by 0.5 C

### ISSUE THREAD

**Issue by taldcroft** [sot/starcheck#146]
After the MP guideline change is approved.

**Comment by jeanconn** [comment]
Not sure why this became two issues.  Closing in favor of #147

**Comment by taldcroft** [comment]
Silly process maneuvering, but one should leave the original issue open until the fix is merged.  (In astropy we are doing a lot less attaching PRs to issues, so this is getting ingrained in me as a habit).

**Comment by jeanconn** [comment]
That's fine.   I'll also stop attaching.  It almost worked out then that you'd made two issues though...

**Comment by taldcroft** [comment]
Attaching is fine for us.  In astropy it has to do with a technicality about the Assignee being the reviewer.

**Comment by jeanconn** [comment]
But if I attach, I have no original issue left to leave open.  I don't understand the plan for process.
