### ISSUE TITLE
Is FigureOfMerit::star_probs just decorative at this point?

### ISSUE THREAD

**Issue by jeanconn** [sot/starcheck#168]
I think that star_probs at

https://github.com/sot/starcheck/blob/f5b9602af68db4cd0a605a93f3dddeebb28368b4/src/lib/Ska/Starcheck/FigureOfMerit.pm#L97

isn't actually called at all now that we're using the acquisition model.

**Comment by taldcroft** [comment]
Sounds about right to me.  I suppose you could delete the code and see if starcheck runs OK.

**Comment by jeanconn** [comment]
So, this routine is the one that attempted to override star probabilities with the actual historical acquisition fraction.  Since it isn't being called anymore, nothing is doing that, and as far as I can tell, acquisition histories don't change current probabilities.  So, do we want to add some code in make_figure_of_merit to do this for the 5y no-ms-flag-equivalent acquisition data?  Or leave this alone?
