### ISSUE TITLE
Include eclipses in thermal model evaluation

### ISSUE THREAD

**Issue by taldcroft** [sot/starcheck#219]
Currently eclipses are ignored in thermal model evaluation (https://github.com/sot/starcheck/blob/c2b31b4a/starcheck/calc_ccd_temps.py#L276).

Eclipse umbra entry/exit times can be found in the backstop file using ORBPOINT events with TYPE = EONIGHT and EODAY, respectively.

**Comment by jeanconn** [comment]
These need to go into cmd_states too right?

**Comment by taldcroft** [comment]
Indeed, cmd_states is the right place for global application to thermal model computation (e.g. ACIS).  I had been thinking of a smaller hack within starcheck (building eclipse intervals from backstop).

This is a slightly oddball case because being in eclipse is not really a command, but it's close enough given that *looks* like a backstop command.  Putting it into cmd_states makes this a noticeably more difficult / time-consuming patch...

**Comment by jeanconn** [comment]
OK, I figured even for starcheck you'd only be halfway there if you just applied eclipses for the schedule interval and not for the propagation interval before schedule start.  Though that's obviously really just a large nit.

I seem to recall that we'd chatted about eclipses and the ACA model at one point but I can't find my notes.

**Comment by jeanconn** [comment]
Also, what should get validated (here or in cmd_states)?  I note that it looks like AOECLIPS seems to be true for more of penumbra, so we could verify that a boolean eclipse state based on EODAY/EONIGHT was fully contained by AOECLIPS == 'ECL ' in telemetry or some such.

**Comment by jeanconn** [comment]
Also, are these in the plans for https://github.com/sot/kadi/pull/42 ?

**Comment by taldcroft** [comment]
Yes! See  https://github.com/sot/kadi/pull/42/commits/0e7e1f344177fb911867a101bb84ecf20c25bb8f

**Comment by jeanconn** [comment]
Awesome 👍

**Comment by jeanconn** [comment]
Noticed again in DEC1718T products

**Comment by jeanconn** [comment]
Likely also an issue in JUN1019A.

**Comment by jeanconn** [comment]
I think this was done in #330
