### ISSUE TITLE
What should we do for color == 1.5 stars?

### ISSUE THREAD

**Issue by jeanconn** [sot/starcheck#226]
Right now they get a yellow warning only if also fainter than 10.0 mag.
Should the mag condition be removed? 
Should this be a yellow or orange warning?
Only guide stars get warnings based on color in the current code.

**Comment by jeanconn** [comment]
This is still an outstanding issue.  @taldcroft What are your thoughts on when you should get a warning and what printed color should that warning have for a guide star with color == 1.5?

**Comment by taldcroft** [comment]
Yellow warning independent of mag.  The mag_err is appropriately large for these, and acq probability appropriately adjusted, so yellow is enough.  But as in the case shown in #232, having *no* indication of this is definitely confusing.

**Comment by jeanconn** [comment]
I should expand this discussion to ACQ.  The section in 

https://github.com/sot/starcheck/blob/f6520a6f51f349c56ea8a08d3f0100218865833a/starcheck/src/lib/Ska/Starcheck/Obsid.pm#L1230

is where all this confusion happens.  Right now stars are assigned a "marginal note" if color == 1.5 *and* mag > 10.0.

If guide stars, they get an orange warning for a color=0.700 "marginal note" and a yellow warning for a 1.5 "marginal note".  

If a star is bad class it will get a warning for both acq and guide.

**Comment by jeanconn** [comment]
OK. So I'll cut the mag dependent logic and let the warning print for both acq and guide stars.

**Comment by jeanconn** [comment]
While I'm at it, should ACQ-only stars get an orange warning for color=0.700 ?

**Comment by taldcroft** [comment]
> While I'm at it, should ACQ-only stars get an orange warning for color=0.700 ?

Sure.

**Comment by jeanconn** [comment]
It looks like removing the mag filter on the 1.5 warning contributes to a lot more text warnings than I would have expected (just didn't realize we use so many of these stars).  Not sure if we want to select these later in selection as well.

**Comment by jeanconn** [comment]
Closed by #233

**Comment by jeanconn** [comment]
Is this noisy enough to hold promotion? (was kinda hoping to get starcheck 11.24 out today, but fine if we defer another week for some more improvements)

Do you want to stop the 1.5 green warnings altogether or make them magnitude dependent again?  I'm guessing from your text that you aren't interested in a more complicated combination of something like "if we've got a measurement of this star within N * mag_aca_err, don't bother with the color=1.5 warning).

Fine with including pos err.  For `mag` do you really just want `mag_err`?  I ask because we've got `mag_aca_err` in the hover over already.  And I still need to finish an update to Ska::AGASC to get VAR from the catalog.  And at some point just use Python to get the stars and do all this.

And sure, it is probably time to update to using the kadi star lookups.  I think they've just been slower to use and slower to update than the current cgi and sybase star database.

**Comment by taldcroft** [comment]
Best to talk about this in person at this point, it's gotten a little complicated.

About the mag err, sorry for being sloppy as I meant mag_aca_err.  But I was referring to the hover-over on the ID in the catalog text, not on the star field image.  I don't want to have to hunt down the star in the image.

And the question about acq prob for bright color=1.5 stars is a good one.   In https://github.com/sot/aca_stats/blob/master/fit_flight_acq_prob_model.ipynb the mean `p_fail` for bright stars (mag_aca < 8.5) is statistically consistent and "small" for both color=1.5 and color != 1.5.  I don't have any validation plots that show mag-dependent trends, but at least from what we know there is not a giant problem.

**Comment by taldcroft** [comment]
As I think about this what I really want as a reviewer is just seeing that "C" comment at the end and probably the line in the star catalog colored green so that it gets my attention.  So I think that is "stop the 1.5 green warnings altogether", but make it easy to find the mag_aca_err in the hover-over in the catalog.

**Comment by jeanconn** [comment]
Sounds good.

**Comment by jeanconn** [comment]
![hover_over](https://user-images.githubusercontent.com/791508/38763699-179c865a-3f6f-11e8-8809-bbe9e900e9f4.png)
