### ISSUE TITLE
Remove quadrant boundary check on guide stars

### ISSUE THREAD

**Issue by jeanconn** [sot/starcheck#231]
Seems like this is just noise after setting SAUSAGE to ignore the quadrant boundaries.

**Comment by taldcroft** [comment]
Agreed.

**Comment by jeanconn** [comment]
Do we still want the check for fid lights close to the boundary or can that go too?

**Comment by jeanconn** [comment]
And if we deprecate one or both checks in the code what changes should I make in the checklist?  Do we just cut the items or cut and re-number (seems wrong) or mark as defunct (maybe best choice) or something else?

**Comment by taldcroft** [comment]
Just cut but do not renumber.  I forget where or if this list is version controlled, but that should be the memory of past list items.

**Comment by jeanconn** [comment]
OK.  I've got it version controlled right here in the starcheck git repo.

**Comment by jeanconn** [comment]
Closed by #234
