### ISSUE TITLE
No color=1.5 indication

### ISSUE THREAD

**Issue by taldcroft** [sot/starcheck#232]
In obsid 49327 in APR0918-pre-release, the ACQ idx=9 star has color=1.5, and this is reflected in the low acq probability for a 9.943 mag star.  But there is no indication of this in the text.  Am I missing something?

**Comment by jeanconn** [comment]
I probably should change the issue title on https://github.com/sot/starcheck/issues/226

**Comment by taldcroft** [comment]
Nice coincidence.  I had not checked all emails from this afternoon.  Closing as this is a repeat of #226.
