### ISSUE TITLE
Add dwell duration checks

### ISSUE THREAD

**Issue by jeanconn** [sot/starcheck#235]
These are PCAD checks that could be added for overlap that coverage

- For maneuvers >  0.9 deg, the subsequent attitude hold duration must be >= 20 min
- For maneuvers <= 0.9 deg, the subsequent attitude hold duration must be >= 4 min 40 sec

**Comment by taldcroft** [comment]
My inclination is to not repeat the PCAD checks.  This is really a PCAD requirement, not ACA.
