### ISSUE TITLE
Report bad pixel offset with sign

### ISSUE THREAD

**Issue by taldcroft** [sot/starcheck#244]
The offset to a nearby bad pixel is reported as the absolute value, but knowing the sign (and the difference convention) would be useful for pre-review.

https://github.com/sot/starcheck/blob/fa0eaad500eef13f13c611d3e9bddd5504f9f7e8/starcheck/src/lib/Ska/Starcheck/Obsid.pm#L1398

**Comment by jeanconn** [comment]
I'm fine with signed offset, but what I really want is the coordinates of the bad pixel in row col (as in, which pixel is the problem).  Which pixel and its last dark current value would be even better.

**Comment by taldcroft** [comment]
Yes even better. There is plenty of room on the line.

**Comment by jeanconn** [comment]
The current imposter warnings  in #276 look like
```
+>> WARNING: [ 5] Imposter mag 11.7 offset 2.9 (row  456, col  299) star ( 461,  300)
```
so I don't have  delta at all (with the idea that if the hot pixel region is anywhere in the dithered box it doesn't matter how close it is from nominal star position).  Good enough for this issue?

The bad pixel warnings currently also don't have the sign but at least have the coordinates of the
closest actual bad pixel.
```
>> WARNING: [ 6] Nearby ACA bad pixel.  row, col (-265, 466), dy, dz (26, 4) 
```

**Comment by jeanconn** [comment]
I should probably update that `offset` to `centroid offset` in the warning (even though the imposter is not guaranteed to cause that centroid offset but).

**Comment by taldcroft** [comment]
Good enough, but change the imposter location to `row, col (456, 299)` and if possible get rid of the extra leading spaces in the numbers.

**Comment by jeanconn** [comment]
OK.  I actually put the spaces there on purpose so these warnings lined up better fixed width (when half have minus signs) but I suppose there's no real win to fixed width in this case.
