### ISSUE TITLE
Downgrade ACQ spoiler and search box size from red to orange

### ISSUE THREAD

**Issue by taldcroft** [sot/starcheck#246]
Seems like these are not really "critical" since they would just result in loss of one acq star (worst case):
- WARNING: [ 5] Search Box Size. Star too faint for > 120 box. 
- WARNING: [ 3] Search spoiler.  738856128: Y,Z,Radial,Mag seps:  86 131 157 -0.1

**Comment by jeanconn** [comment]
OK.  I had the spoiler one as #236 but didn't have the search box one.

**Comment by taldcroft** [comment]
This came up again in MAR0419 with obsids 48343 and 48342.  Both of those critical warns should be orange.  

Eventually when we have enough flight experience with proseco then we may downgrade further.  Basically proseco has a nuanced way of dealing with spoilers and human intuition may not be helpful.  I suspect that spoiler messages will cease to be actionable.

**Comment by jeanconn** [comment]
Thought I also don't think starcheck separates out spoiler handling for acq and guide much, so probably will need to do that too.

**Comment by jeanconn** [comment]
I assume for this issue you are mostly talking about downgrading ACQ warnings only, right @taldcroft ?

**Comment by taldcroft** [comment]
Yes I am just thinking of acq warnings.

**Comment by jeanconn** [comment]
For the search box one, I suggest just cutting the warning altogether in #300 .

**Comment by jeanconn** [comment]
Search box size done in #300 .  Spoiler warning is in #236 so closing this issue.
