### ISSUE TITLE
Fid in acq box check should have margin for fid position uncertainty

### ISSUE THREAD

**Issue by taldcroft** [sot/starcheck#251]
Probably 25 arcsec is reasonable.  This accounts for the actual position uncertainty < 15 arcsec plus a couple of pixels.  (E.g. actual PEA readout box can be a pixel larger than expected due to 2x2 binning, and the fid has a broad PSF).

![image](https://user-images.githubusercontent.com/348089/44618436-ba7f9a00-a843-11e8-868e-2a95a1555a19.png)

https://github.com/sot/starcheck/blob/5879961efec6378b5900f34714c04a193cba22e8/starcheck/src/lib/Ska/Starcheck/Obsid.pm#L1305

**Comment by jeanconn** [comment]
Do you want to remilestone this to 13.1 as well @taldcroft or just add 25 arcsecs to halfw on this check for 13.0?
