### ISSUE TITLE
Acq star off padded CCD warning is incorrect

### ISSUE THREAD

**Issue by taldcroft** [sot/starcheck#306]
I haven't looked at the starcheck code, but e.g. in .../2019/APR0119/oflsa/starcheck.html#obsid21802 it gives this warning:

>> WARNING: [ 9] Acq Off (padded) CCD (P_ACQ should be < .5)

The listed acq probability is 0.642.  I've checked that proseco code pretty carefully a couple of times and written tests, and to the best of my knowledge it is correct.

**Comment by jeanconn** [comment]
The starcheck code was just set to put in this warning for anything off the dither-padded ccd based  on your comment (with no proseco calc).   Certainly can cut if has no value at this point.  If the calculation of the dither padded useable CCD edge is wrong etc that's another issue.

**Comment by taldcroft** [comment]
I would say to downgrade this to Info and cut the `(P_ACQ should be < .5)`.

**Comment by jeanconn** [comment]
Closed by #358
