### ISSUE TITLE
Apply effective temperature "penalty"

### ISSUE THREAD

**Issue by jeanconn** [sot/starcheck#308]
Since the starcheck calls to the proseco stuff are constructing an acq catalog from the commanded catalog and then getting calc_p_safe, I think the the proseco get_effective_t_ccd method is never called.

We probably want to use the penalty on the starcheck side too (for the time being, until sparkles checks are properly integrated).

**Comment by taldcroft** [comment]
I *think* this should be fairly trivial, namely just replace the call to `get_acq_catalog` to `get_aca_catalog`, with a few tweaks to the kwargs.  The use `aca.acqs` instead of `acq_cat`.  

Going through the `cat_aca_catalog` function will engage the effective temperature machinery.

**Comment by taldcroft** [comment]
Which points to a general API recommendation of always using `get_aca_catalog` for making catalogs, even if only an acq catalog is desired.

**Comment by jeanconn** [comment]
Right, I think we had a bunch of proseco API changes after I figured out something for starcheck and I wasn't sure if this transition was worth it until we had `include_ids_fids`.

**Comment by jeanconn** [comment]
Closed by #309
