### ISSUE TITLE
Use RUNNING_LOAD_TERMINATION_TIME for ACA thermal propagation

### ISSUE THREAD

**Issue by taldcroft** [sot/starcheck#340]
I believe that the following lines are the key ones for taking advantage of `RUNNING_LOAD_TERMINATION_TIME` and `SCHEDULED_STOP_TIME` commands if available.  The idea is to override `tstart` and `tstop` with those command times.

https://github.com/sot/starcheck/blob/74cac71763f88deb143bd179bd343eb988332b6b/starcheck/calc_ccd_temps.py#L155

At the point below, with the new version of `tstart` it is possible that `cmds` is not time-ordered, so that needs to be taken care of.  (This is a consequence of the fact that schedule commands can overlap.)

https://github.com/sot/starcheck/blob/74cac71763f88deb143bd179bd343eb988332b6b/starcheck/calc_ccd_temps.py#L313

**Comment by jeanconn** [comment]
Yes.  This is about what I figured.  

For special cases, I'm not sure that we're all set for timelines processing.  I don't know what I expect to see in the command load processing generation summary for a "first command time" if RUNNING_LOAD_TERMINATION_TIME is set to be... early.  Take away is that it should be fine to get this right for load review in thermal model tools but I don't think I have quite enough info yet to make sure it ends up in the database correctly.

**Comment by taldcroft** [comment]
>  I don't know what I expect to see in the command load processing generation summary for a "first command time" if RUNNING_LOAD_TERMINATION_TIME is set to be... early. 

No change in that file since it is created by OFLS not backstop. 

I confess I've never understood that file and precisely why we need it.  I might have understood at some point but have forgotten in the mean time.  With the abolishment of replan/reopen, is it still required?  What is taken from that which is required for timelines?  What is the need for distinguishing a replan load from a load?

**Comment by jeanconn** [comment]
Good points all.  I'd have to dig in to that code for more fundamental understanding, but IIRC, I'm using the processing summary to determine the start and stop times for the commands that were in each CLD when made.

Maybe it won't make a difference and maybe we won't care.  If the times in iFOT will still represent the range of times from each load segment that were run, and we can trace those back to a backstop file via CLD name, its probably fine.

IIRC I think I was also using the stop time of the CLD to somewhat infer early terminations in the schedule_view application; maybe with this SCHEDULED_STOP_TIME we won't need to infer anyway.  Not much using schedule_view anyway as far as I can tell.

**Comment by jeanconn** [comment]
Looking back at this in passing, I'm not sure what "At the point below, with the new version of tstart it is possible that cmds is not time-ordered, so that needs to be taken care of. (This is a consequence of the fact that schedule commands can overlap.)" really means and how the new tstart could put the cmds out of order.

**Comment by taldcroft** [comment]
Because there can be commands at the end of the continuity loads which are after the initial commands in the loads being reviewed.  In practice I think this is mostly AOACRSTD (or something like that), disable AC processing restart that gets the -3 min offset.  The point is that if you just concatenate the continuity load commands and the review load (backstop) commands they can be out of order.  This was always a possibility so maybe the sorting is already happening.

**Comment by jeanconn** [comment]
Ah. OK.  I thought those AOACRSTD commands were generally at the beginning of the loads being reviewed not at the end of the continuity, but that's fine.

But are you saying that we expect RLTT to explicitly not be the first command in the loads being reviewed (explicit load interaction)?  Or we just don't care?

**Comment by taldcroft** [comment]
AOACRSTD *is* often at the beginning of reviewed loads, that's what I meant, and can be before the last commands (by time) in the continuity loads.  We don't care where RLTT occurs, and it might not be the first command in loads.

**Comment by jeanconn** [comment]
OK.  

cmds.add_cmds looks to have a sort so should be fine either way.

https://github.com/sot/kadi/blob/a3389dd91e71c9ccd2af58aa85a31a35fb38e471/kadi/commands/commands.py#L334

**Comment by jeanconn** [comment]
In starcheck for continuity, it looks like the hopper pieces are working from the History files so that is OK for now.

The dither continuity is now using kadi 

https://github.com/sot/starcheck/blob/ecc340c94a8154719e9de12c8b4f0104a0e57954/starcheck/src/starcheck.pl#L406

I'm trying to think of a way where this could matter for RLTT.  If RLTT is set to a day before the rest of the backstop commands, for example, it will be the first backstop command and this logic will work.  If it *isn't* the first backstop command and we have some *desire* for onboard load interaction I don't see how that is going to work with the dither state building we have anyway.

**Comment by jeanconn** [comment]
Did you have any thoughts on my last comment @taldcroft ?  I realize this issue was only about thermal propagation.  I suppose I really just wonder if we want a warning on overlapping commands.

**Comment by taldcroft** [comment]
No warning on overlapping commands.  That is a normal and acceptable situation, with no action required.  However the code needs to handle this correctly.

> If it isn't the first backstop command and we have some desire for onboard load interaction I don't see how that is going to work with the dither state building we have anyway.

In practice there won't be overlapping dither commanding, so here perfection is not required.  So instead of getting dither continuity at `$bs[0]->{date}` you need to get it at RLTT.

**Comment by jeanconn** [comment]
And if RLTT is not the same as the first command, will the History go up to RLTT or stop at Backstop start?

**Comment by jeanconn** [comment]
And my point was not to get nit-picky.  I'm not shooting for perfection.   My point was that the two data sources (backstop in review, kadi command states) seem to have a conceptual divide that starts at backstop start that is not changed by this new concept of RLTT, and that if we're constructing and checking new dither states from the backstop in review, that starting from the initial state at `$bs[0]->{date}` still makes sense.  But RLTT probably won't be different from `bs[0]->{date}` anyway.

**Comment by jeanconn** [comment]
I'll add a comment at:
```
https://github.com/sot/starcheck/blob/ecc340c94a8154719e9de12c8b4f0104a0e57954/starcheck/src/starcheck.pl#L406
```
To explain that in the RLTT era the RLTT "pseudo-command" will be the first command and this will still just work.
