### ISSUE TITLE
Warn for ACA T_ccd below -14 C for OR's

### ISSUE THREAD

**Issue by taldcroft** [sot/starcheck#386]
Per discussion at SSAWG on 2022x06x08, there is a risk of not acquiring fid lights if the CCD temperature goes below -14 C.

NB: this may be refuted by historical data at colder temperatures. We updated the commanded fid locations at some point which is probably captured in the OFLS or MATLAB characteristics.

**Comment by jeanconn** [comment]
Alignments break my brain, but I would think that older data that "refutes" this would predate the last aimpoint shift.

**Comment by taldcroft** [comment]
Good point. We have not getting below -14 C with any regularity since the 2018-Oct safe mode and IRU swap. And that one was a big jump of 12 arcsec. Without trying to figure out signs, it is probably the case that the 12 arcsec is in the direction where we are now pushing the search box edge limit.

So we should just put this into starcheck.

<img width="547" alt="image" src="https://user-images.githubusercontent.com/348089/173398946-76da76c6-4d26-4ffe-a4c8-2ba5bc505e2a.png">

**Comment by jeanconn** [comment]
Since this is about fid tracking, I should have implemented this with the acquisition temperature instead of the min observation temperature.  But might end up being OBE.
