### ISSUE TITLE
Dither/spoiler checks use OR dither instead of commanded dither

### ISSUE THREAD

**Issue by jeanconn** [sot/starcheck#66]

**Comment by jeanconn** [comment]
Looks like all ERs are also checked with 20 arcsec dither.

**Comment by jeanconn** [comment]
Do we want a comment if an observation is checked with default 20 arcsec dither (because that's all we have available from commands and history) but has an OR for 8?  Or do we just not care about being informed about this conservatism?

**Comment by taldcroft** [comment]
Short answer for starcheck is we don't *need* to be informed about this conservatism.  

Longer: there are two distinct checks here, spacecraft safety (can be done from commands (with initial conditions) purely, and whether the commands match the intended configuration (commands vs. OR list).  Going forward the code will generally be careful about this distinction.

**Comment by jeanconn** [comment]
I think this is closed by #131
